### PR TITLE
Disable pickling by default

### PR DESCRIPTION
**Pull request by tedmiston**
see https://github.com/astronomerio/astronomer/issues/123

### CODE REVIEW

**Comment by tedmiston** [comment]
Are we cool with having an opinionated default like this?  If not, I'm thinking I could instead copy this over as an example in our docs.

What do you guys think? @schnie @andscoop @cwurtz

**Comment by schnie** [comment]
@tedmiston isn't pickling only required for the mesos executor? Does anything else use this setting? I'm assuming we aren't currently utilizing pickles, but want to make sure.

**Comment by tedmiston** [comment]
The error @vparekh94 got without this setting was in our current Astro Open setup trying to use VirtualenvOperator (haven't tested this myself).

My understanding is that any executor besides LocalExecutor and SequentialExecutor at least pulls it and potentially uses it.

https://github.com/apache/incubator-airflow/blob/b0061f1369636c86df87829b93d5ece582591e2a/airflow/jobs.py#L2501-L2508

https://github.com/apache/incubator-airflow/blob/fa6c35743a5129057d870752554b0827dd7d462f/airflow/models.py#L4068

**Comment by vparekh94** [comment]
@tedmiston so doing some digging, it looks like the PythonVirtualEnvOperator does pickle the DAG if arguments are passed to it:

https://github.com/apache/incubator-airflow/blob/master/airflow/operators/python_operator.py#L184

https://github.com/apache/incubator-airflow/blob/master/airflow/operators/python_operator.py#L311

I was able to get an example to run without overriding the pickling setting after I took out passing context and `kwargs` to the operator.

**Comment by tedmiston** [comment]
Cool - sounds like it's relevant when the op has context / kwargs / args passed to it.

I'm ready to merge this if someone can give a 👍.

**Comment by schnie** [comment]
So it looks like the issue @vparekh94 hit, may be related to pickling, but I'm not sure `donot_pickle` is actually used by the `PythonVirtualEnvOperator`. Seems like that's a different issue. @tedmiston have you tested this with the CeleryExecutor to be sure?

**Comment by tedmiston** [comment]
I haven't tested it with that operator personally yet.  Since this is more maintenance, I think this is lower priority than the sprint —  cool if we revisit this post-sprint?

**Comment by schnie** [comment]
Yep

**Comment by ryw** [comment]
lets just merge this, shouldn't hurt anything right?

**Comment by schnie** [comment]
Let's merge it after we test it. @tedmiston can you test this quick? We should start testing PRs _before_ sending them to prevent them from lingering around like this.

**Pull request closed without merging**
