### PR TITLE
Use portable shebangs

### PR DESCRIPTION
**Pull request by tedmiston**
Similar to https://github.com/astronomerio/astronomer-ee/pull/12

### CODE REVIEW

**Comment by tedmiston** [comment]
@schnie Does this one look good to merge to you?

**Comment by schnie** [comment]
@tedmiston `bash` is cool for anything that runs outside of the container but for everything that runs inside an alpine container, I'd rather they stay `sh`. Typically we wouldn't want to even install bash in our containers - airflow is the special case here. Keeping them `sh` will actually make them more portable within our ecosystem.

**Comment by tedmiston** [comment]
Makes sense.  Do you think it'd be preferred to use sh over bash in the docker entrypoint too, or is there something about it that depends on bash instead?

https://github.com/astronomerio/astronomer/blob/9527b7a219765e72b63a9c36d3c9aa843e99c195/docker/platform/airflow/include/entrypoint#L1

**Comment by schnie** [comment]
Something in the entrypoint or wait-for-command scripts needs bash but could probably be patched to work with sh. I just left it so users could use the bash operator from airflow.

**Comment by tedmiston** [comment]
Makes sense - closing this PR.

**Pull request closed without merging**
