### PR TITLE
Upgraded version of pip to 10.0.0

### PR DESCRIPTION
**Pull request by vparekh94**
Added upgraded version of pip in Dockerfile.

### CODE REVIEW

**Comment by tedmiston** [comment]
@vparekh94 Is this tested?  pip 10 has some breaking changes.

**Comment by vparekh94** [comment]
@tedmiston I was able to successfully build locally with a few requirements in there. 

There's more info here:
https://github.com/astronomerio/astronomer-ee/issues/73

**Comment by tedmiston** [comment]
LGTM

**Comment by schnie** [comment]
```
Collecting pandas<1.0.0,>=0.17.1 (from apache-airflow[celery,devel_ci,redis,statsd])
  Downloading https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz (11.3MB)
  Could not find a version that satisfies the requirement Cython (from versions: )
No matching distribution found for Cython
The command '/bin/sh -c apk add --no-cache --virtual .build-deps                build-base              cyrus-sasl-dev          freetype-dev            git             krb5-dev                libffi-dev          libxml2-dev              libxslt-dev             linux-headers           mariadb-dev             postgresql-dev          python3-dev     && apk add --no-cache           bash            mariadb-client-libs         postgresql               python3                 tini    && pip3 install --no-cache-dir --upgrade pip==10.0.0    && pip3 install --no-cache-dir --upgrade setuptools==39.0.1     && pip3 install --no-cache-dir "${AIRFLOW_MODULE}"   && apk del .build-deps  && ln -sf /usr/bin/python3 /usr/bin/python      && ln -sf /usr/bin/pip3 /usr/bin/pip' returned a non-zero code: 1
```
@vparekh94 @tedmiston we need to back this out.

**Comment by tedmiston** [comment]
Whoops — I'll revert and comment back on https://github.com/astronomerio/astronomer-ee/issues/73.

**Pull request merged**
