### PR TITLE
Dockerfile enhancements

### PR DESCRIPTION
**Pull request by tedmiston**
This PR improves consistency and simplifies a couple commands in our Dockerfiles.

### CODE REVIEW

**Comment by schnie** [comment]
Looks good, did you happen to test building and running these images?

**Comment by tedmiston** [comment]
I tested the command changes I made in a bash shell on the fly before committing them in the GitHub UI.  I haven't done a full build test yet.

**Comment by schnie** [comment]
I'd say just try and run a `make` today and see if you can run an open example just to make sure we're clean.

**Comment by schnie** [comment]
Untested, can't merge until we know everything works. @tedmiston you can probably test this while your working through the Grafana upgrades.

**Pull request closed without merging**
